# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Release"

on:
  # No checks for branch or repo - assuming release creation is manual, controlled
  release:
    types:
      - created
    branches: [release-4*]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Release"
    if: startsWith(github.repository,'odpi/')
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          # Java 17 is used for final released build
          java-version: '17'
          distribution: 'temurin'
      - name: Build and publish to Maven Central
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: build publish -Dorg.gradle.parallel=false
        env:
          OSSRH_GPG_KEYID: ${{ secrets.OSSRH_GPG_KEYID }}
          OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          OSSRH_GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v3
        with:
          name: Assemblies
          path: |
            connector/build/libs/*.jar
            migrator/build/libs/*.jar
